### PR TITLE
Add dracula wallpaper

### PR DESCRIPTION
**Pull request by ericdallo**
I made a NixOS wallpaper inspired on [Dracula's theme](https://draculatheme.com/), we can open a PR on Dracula latter referencing NixOS later if we want.

nix-wallpaper-dracula

### CODE REVIEW

**Comment by ericdallo** [comment]
Done @samuelgrf !

**Comment by samuelgrf** [comment]
Nice, now squash both commits so we don't have the huge older version bloating the git history.

**Comment by ericdallo** [comment]
Done @samuelgrf !

**Comment by samueldr** [comment]
I do not know that we want to accept new "all rights reserved" artwork in this repository.

I also do not know how using the Nix Snowflake, which is "CC-BY", affects the copyright / license ability of this contribution.

The current "all rights reserved" files were kept only because they were already part of the repository. See #17 and #23..

I would only be comfortable merging this contribution if it had a license which allows redistribution, at the very least. Hopefully it would also allow derivative work, considering what NixOS and FLOSS is :).

**Comment by ericdallo** [comment]
I see @samueldr, I don't see any problem in changing the license to a license that anyone can use, can you point what license should I use? or point to an example of that?

**Comment by samueldr** [comment]
Most [Creative Commons licenses](https://creativecommons.org/licenses/), if not all, would do. There is work under cc0 already, and some under BY-SA.

For my personal work I added the "(by nixos-artwork)" mention, meaning that the attribution is for "nixos-artwork". This is not required.

**Comment by ericdallo** [comment]
Thank you @samueldr 
Done!

**Pull request merged**
