### PR TITLE
Update IRC reference

### PR DESCRIPTION
**Pull request by rgrmrts**
Updating README.md to reflect the IRC changes freenode -> libera.chat (see https://nixos.wiki/wiki/Get_In_Touch)

### CODE REVIEW

**Review by jonringer — APPROVED** [review]

**Comment by jonringer** [comment]
thanks!

**Comment by samueldr** [comment]
Um, this is not quite right. We've moved to Matrix, mostly.

ref: https://github.com/NixOS/nixpkgs#community

**Comment by jonringer** [comment]
well, it's right for IRC.

although, matrix would probably be the most correct communication platform

**Comment by rgrmrts** [comment]
Thanks for the review and merge @jonringer 

Thanks for pointing that out @samueldr, I can make some follow-up PRs to update the `README.md` stuff to suggest Matrix as the primary communication platform!

**Pull request merged**
