### PR TITLE
logo: Add raccoon logo for 22.11 release

### PR DESCRIPTION
**Pull request by rwxg**
@ners made me do it

### CODE REVIEW

**Comment by ners** [comment]
@samueldr with the release around the corner, can we get this reviewed and possibly merged?

**Comment by samueldr** [comment]
Hi! :wave: 

Thank you for your contribution!

So, the process for release logos is as such: deciding on whether it is chosen or not should rest on the release managers. Though I can and will provide technical guidance as needed.

But, even then, I guess I can share some inputs, assuming this one is desired by the RMs.

* * *

### Technical notes

(These problems must be solved)

@rwxg, you said [*“I realised that I borked the colour profile during the previous export”*](https://github.com/NixOS/nixos-artwork/issues/90#issuecomment-1291792431), I think it's still the case? Though differently.

AFAIK no profile should be used here. I lack proper experience with using colour profiles to be sure how to guide you.

Though I know the resulting images should have these colours at the extremeties of the lambdaflake branches:

 - https://github.com/NixOS/nixos-artwork/tree/master/logo#colours

If there's confusion, or anything to discuss about for colour profiles, do say. You could look at the previous XCF and PNG files I suppose?

* * *

### Personal notes

I like the composition [placement of things]. I also like the composition of the other attempt, the lazy one. I would go as far as saying I prefer it because it is less busy, but that's, like, my opinion. Either of them are well composed.

I still don't like the tiny snowflake in the critter friend hands, like [stated](https://github.com/NixOS/nixos-artwork/pull/81#issuecomment-1075736499) [previously](https://github.com/NixOS/nixos-artwork/pull/83#pullrequestreview-971447674), but this is definitely my opinion...

... except for one detail, which I think almost goes in technical notes: cutting that shape out from the main lambdaflake should probably be forbidden entirely. Still my personal opinion, but this one I hold more strongly.

**Comment by rwxg** [comment]
Hello!

Thanks for the feedback - you are right, the colours on the flake still weren't as they ought to be. They should now match the exact hex values listed in the readme. The same treatment was given to the lazy variant, should the RMs decide on using that particular one, in which case I'll provide those files.

Regarding the broken-off flake bit, I'll quickly patch that up if so desired.

**Comment by mweinelt** [comment]
The genereal idea that the raccoon would steal part of our logo was nice, but modifying the logo that way is apparently a no-no.

**Comment by rwxg** [comment]
Too bad, but fair enough. I went and glued it back together.

**Review by ners — APPROVED** [review]

**Review by mweinelt — APPROVED** [review]

**Comment by Ma27** [comment]
@mogorman (or anyone else) is some merch available for this one anywhere? :sweat_smile:

**Pull request merged**
