### PR TITLE
Add yet another wave of 3D wallpapers

### PR DESCRIPTION
**Pull request by MultisampledNight**
This adds another wave of 3D wallpapers, which are more of a modern take than a simple one.

A few questions:
- I also created a .blend file of the logo, should I submit that one, too?
- One .blend source file is really big (gear.blend with ~90 MiB), which even caused a warning suggesting to use Git LFS. Should I just delete the sources? Switch to Git LFS? Use another file format?
- For the sources, I created a subfolder `source` in `wallpapers` to avoid cluttering the `wallpaper` directory itself. Is that okay?

### CODE REVIEW

**Comment by MultisampledNight** [comment]
Sorry if this comes over as rude, but is it possible that new wallpapers are unwanted _in general_? #66, #41, #60 and #68 have all been laying bare for quite a while. If that's the case, it'd be nice to add a note to the README listing that new wallpapers are not wanted.

**Comment by jonringer** [comment]
I think the main thing is that not a lot of people are subscribed to this repo.

Personally, I think they look really cool!

cc @samueldr

**Comment by dasJ** [comment]
Are there even people who can merge here apart from the RMs?

**Comment by dasJ** [comment]
I guess not

**Pull request merged**
