### PR TITLE
21.05 okapi release artwork

### PR DESCRIPTION
**Pull request by mogorman**
image

### CODE REVIEW

**Comment by samueldr** [comment]
cc @NixOS/nixos-release-managers

**Review by samueldr — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
Love it, thanks @mogorman

**Comment by Ma27** [comment]
@mogorman thanks! May I ask if there are any plans to make them available on Redbubble? I'm pretty sure that a few of my colleagues (including me) may be interested in ordering release merch :)

**Comment by mogorman** [comment]
yes ill update merch today!

**Pull request merged**
