### PR TITLE
feat: Add a thumbnails directory

### PR DESCRIPTION
**Pull request by bryanhonof**
So other people can also use it, this PR includes the template I used
for the Summer of Nix Public 2022 Lecture Series' thumbnails. I plan on
also including a script that generated those thumbnails, but it's a bit
hacky at the moment. 😅

### CODE REVIEW

**Comment by mweinelt** [comment]
Why is the flake cut off on the right side?

**Comment by bryanhonof** [comment]
@mweinelt Could you perhaps send a screenshot of what you're seeing? I don't think I see the same artifact as you.

**Comment by mweinelt** [comment]
image

when viewing it here on GitHub.

**Comment by mweinelt** [comment]
Screenshot 2022-11-15 at 13-43-48 feat Add a thumbnails directory by bryanhonof · Pull Request #85 · NixOS_nixos-artwork

**Comment by bryanhonof** [comment]
Interesting, this is what I see.
image
The font even looks different, I think. 😄
Perhaps a browser/github issue?

**Pull request merged**
