### PR TITLE
ofborg: Add an assimilated NixOS lambda logo

### PR DESCRIPTION
**Pull request by samueldr**
The starfield might seem a big bright when exported at its 1:1px resolution, but when shown in smaller scales, it basically vanishes. A proper authoring/publishing format pair for icons could solve that issue, but alas only haiku icons do this.

Here it is exported at 48 and 96 px.

ofborg@48

ofborg@96

* * *

I was discussing in private about semi-related topics with @RaitoBezarius, which sparked the idea I applied here.

cc @zimbatm, @mweinelt  for infra reasons. Not sure who else to ping for ofborg organizational setup.

Also cc @grahamc, I believe you wanted your likeness to be removed from that project a few years back.

### CODE REVIEW

**Comment by zimbatm** [comment]
Nice!

I wanted to apply the change, but https://github.com/ofborg holds the GitHub app and is probably owned by Graham only. @grahamc, if you give me ownership of the org, I can do some cleanup and integrate it with the rest. We're also a bit stuck due to the need for SSH access on the ofborg machine in the infra team. If that wasn't the case, I could suggest creating a new app since Graham is so busy.

**Comment by samueldr** [comment]
:x: needs an entry in `CONTRIBUTORS.md`

**Comment by drupol** [comment]
@zimbatm Got news from @grahamc since then?

**Comment by zimbatm** [comment]
No news.

@cole-h would it be useful to share the ofborg org with the infra team?

**Comment by drupol** [comment]
@cole-h @grahamc Can you please let us know if you plan to do something for this?

**Comment by cole-h** [comment]
I am still in the process of making ofborg generally accessible to the infra-build team. Once this is done, I'd be glad to add the infra-build members to the `ofborg` GitHub organization and let them do as they will with ofborg.

My goal is to have this done by the end of the month.

**Comment by drupol** [comment]
@cole-h What's the status of this? Did you succeed to finally add the infra-build members to the `ofborg` organisation ?

Thank you.

**Comment by drupol** [comment]
> My goal is to have this done by the end of the month.

@cole-h Could you please let us know what is going on? Or just specify for which month you were thinking about ;)

**Comment by cole-h** [comment]
Sorry, I got sick, then busy, then distracted and busy. I've finished the migration and have added @zimbatm and @mweinelt to the ofborg org (which includes giving them access to manage the GitHub app, so they can change the logo at their leisure).

**Comment by grahamc** [comment]
fwiw I'm not part of the org anymore, but just happened to look at my mail when @cole-h's notif came through. looks good to me :)

**Pull request closed without merging**
