### PR TITLE
logo: Add rainbow variant

### PR DESCRIPTION
**Pull request by piegamesde**
June is already halfway over, but it's never too late

### CODE REVIEW

**Comment by the-furry-hubofeverything** [comment]
Personally, I don't like the gradient, but I think this is a great idea!

**Comment by piegamesde** [comment]
Yeah, it's up to discussion. An earlier draft didn't have them and I thought it looked too much like the rainbow Aperture Science logo :D

image

I also did some experiments with drop shadows with I personally liked, but I fear that overall they won't fit the overall style guidelines

**Comment by djacu** [comment]
I think both look nice but I really do like the gradient look.

**Review by mweinelt — APPROVED** [review]
Looks great. Please send it!

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
I guess I can abuse my right to merge here if there are no objections in the next few hours.

**Comment by goyalyashpal** [comment]
> deviating from the original colors of the flag
> \- @piegamesde at _https://github.com/NixOS/nixos-artwork/pull/133#issuecomment-2167776315_

hi!  which flag?  i am new to nixos, and the logo on nixos.org/ and manual.nixos.org/ was plain-ish colored.  as someone with interest in graphics design, i am curious how these colors were came up with.

**Comment by piegamesde** [comment]
The rainbow flag: https://www.flagcolorcodes.com/pride-rainbow

The logo currently displayed on nixos.org was not done by me, so I can't tell you about its colors. Ask the marketing team for more information on that

**Pull request merged**
