### PR TITLE
matrix: add doom emacs

### PR DESCRIPTION
**Pull request by ckiee**
For the newly created #doom-emacs:nixos.org.

cc @samueldr, tried not to change the diff dramatically even though inkscape wanted to.

### CODE REVIEW

**Comment by samueldr** [comment]
I don't think it's an issue if the diff is big; I assume inkscape output to be opaque. They are *inkscape source files*, not SVG files for direct consumption.

**Comment by ckiee** [comment]
@mweinelt poke, this should be a quick merge

**Comment by mweinelt** [comment]
Can't merge here anymore.

**Comment by ckiee** [comment]
Do you know who to poke?

**Comment by mweinelt** [comment]
S. D.-R.

**Comment by ckiee** [comment]
poke @samueldr

**Comment by samueldr** [comment]
Haven't looked at the image, but assuming it's okay, given the participants.

**Pull request merged**
