### PR TITLE
20.03 Markhor art work

### PR DESCRIPTION
**Pull request by mogorman**

### CODE REVIEW

**Comment by davidak** [comment]
Thanks for creating the artwork again. It looks very good!

I think there is an issue with the perspective. When we assume the parts of the NixOS logo are on the same layer, why is one horn in front of it and the other behind?

The head is turned right, so the left horn should be closer to the viewer and maybe in front of the logo part.

Here is my ugly mockup:

markhor

**Comment by mogorman** [comment]
i changed it like you requested.

**Comment by mogorman** [comment]
i think it looks better with whole head through the nixos logo though

**Comment by samueldr** [comment]
SInce it's not obvious from looking at the commits,

It went from:

 * original with "wrong" horn perspective
 * davidak's proposal of the right hown
 * head completely poking through

I do like the head completely poking through. :+1: 

Thank very much, again, @mogorman !

@worldofpeace if you can approve, this can be merged :).

**Pull request merged**
