### PR TITLE
Add 23.11 Tapir artwork

### PR DESCRIPTION
**Pull request by riotbib**
This commit adds artwork to the NixOS 23.11 release featuring a Tapir.

The logo was taken from [NixOS/nixos-artwork](https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg).

The image of the Tapir was [taken from Pexels](https://www.pexels.com/photo/malayan-tapir-15401340/), which allows the free use of their pictures without credit, which is beneficial to the nature of this kind of artwork.

I have cropped the picture and turned down the saturation, because there were discolorations at the nose and ears of the Tapir.

I am open to all kind of feedback!

### CODE REVIEW

**Comment by the-furry-hubofeverything** [comment]
Heya!

There's a thin white border around the base of the Tapir's neck. Also IMO I think the contrast on the tapir is not enough to distinguish its features, and is generally a bit dark.

Is there a project file for this?

**Comment by the-furry-hubofeverything** [comment]
By the way, I've never contributed or made comments on nixos-artwork, so please let me know if I'm too nitpicky. I have *some* experience with graphic design.

**Comment by riotbib** [comment]
> There's a thin white border around the base of the Tapir's neck. Also IMO I think the contrast on the tapir is not enough to distinguish its features, and is generally a bit dark.

Thanks, I fixed the border line. And increased exposure and shadows.

Do take a second look if you all want.

> Is there a project file for this?

Yea, but it's proprietary. I'd drop it here, but GitHub prohibits uploads of .psd files.

I'll leave you the cutout Tapir with less saturation here, so you may give it a try if you want!

tapir-cutout-lesssaturation

> By the way, I've never contributed or made comments on nixos-artwork, so please let me know if I'm too nitpicky. I have *some* experience with graphic design.

No, worries. It's appreciated!

**Comment by the-furry-hubofeverything** [comment]
tapir

Did a little fiddling - 

- Readjusted levels (this is what I meant by making the features look more apparent)
- Used a clip mask to round off the neck cutoff
- realign and readjusted angles

I used `nix-snowflake.svg`, Inkscape for the layout and clipping, and krita for the level adjustment

Inkscape source file: [tapir-embedded](https://github.com/NixOS/nixos-artwork/assets/53921912/8f740d2a-52b5-4e4a-a4f4-3d7e1e3f1185) (under CC BY-SA 4.0)

If I had a bit more energy, I want do a bit more (maybe even draw something), but for now this is what I suggest.

**Comment by riotbib** [comment]
Looking good! Please do make a second PR, if you want to. I'd guess this would be the easier way to contribute in this case.

> Inkscape source file: [tapir-embedded](https://github.com/NixOS/nixos-artwork/assets/53921912/8f740d2a-52b5-4e4a-a4f4-3d7e1e3f1185) (under CC BY-SA 4.0)

With all due respect, I do not know if CC-BY et al is doable for this kind of artwork and publication, because then this attribution and license would need to be printed at all use cases, which was not done before. Happy to discuss this.

**Comment by the-furry-hubofeverything** [comment]
> Looking good! Please do make a second PR, if you want to. I'd guess this would be the easier way to contribute in this case.
> 
> > Inkscape source file: [tapir-embedded](https://github.com/NixOS/nixos-artwork/assets/53921912/8f740d2a-52b5-4e4a-a4f4-3d7e1e3f1185) (under CC BY-SA 4.0)
> 
> With all due respect, I do not know if CC-BY et al is doable for this kind of artwork and publication, because then this attribution and license would need to be printed at all use cases, which was not done before. Happy to discuss this.

As the Nix Logo is under CC BY 4.0, I don't see why the release logo can't be under CC BY-SA 4.0.

**Pull request closed without merging**
