### PR TITLE
Add "Binary" wallpapers

### PR DESCRIPTION
**Pull request by intergrav**
Small set of wallpapers I made. Licensed under CC BY-SA 4.0. The binary code in the background translates to "NixOS"

# Preview

Black
Blue
White
Red

### CODE REVIEW

**Review by djacu — APPROVED** [review]
super cool

**Comment by djacu** [comment]
> Hi, very awesome wallpapers. Is there a larger version or a SVG available? I have a 5K display.

@intergrav ^^^

**Comment by intergrav** [comment]
I can make one, give me one sec :)

**Comment by intergrav** [comment]
@djacu @Guanran928 https://github.com/NixOS/nixos-artwork/pull/131

**Comment by FunProgramer** [comment]
Sorry for getting off-topic here:
@intergrav How did you create this wallpapers? Maybe you can give me/publish the source?

**Comment by pmnlla** [comment]
Hello! Just quickly popping back in to ask for the soruce for the wallpapers?

**Pull request merged**
