### PR TITLE
20.09-nightingale artwork

### LINKED ISSUE #56: 20.09 logo
We need a logo for 20.09

cc @mogorman

### PR DESCRIPTION
**Pull request by mogorman**
resolves #56

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Nice.

**Comment by samueldr** [comment]
@worldofpeace @jonringer

Since you're RMs, looking for feedback / approval.

**Review by samueldr — APPROVED** [review]

**Comment by worldofpeace** [comment]
I'm not too crazy that it's showing the nightingale in a screeching pose. I feel like it's distracting/shouting at me which is hard on the eyes.
I would prefer if more of the wings could be displayed and also be like a profile https://2.bp.blogspot.com/-1e3qQwESfsE/UMVXK16NczI/AAAAAAAAOUk/7AN5gNrGxd0/s400/nightingale-.gif. It's a more flattering pose IMHO.
Let me know what you think @mogorman.

**Review by jonringer — APPROVED** [review]
LGTM

then again I'm usually one of those people you don't want to bring along for making design choices because I'm a little too easy to please

I think the "screeching" gives it some energy. And good usage of the nixos logo as a perch ;)

**Comment by mogorman** [comment]
l liked the singing nightingale because i thought had more energy. i'm happy to change it though if others disagree.

**Review by worldofpeace — APPROVED** [review]

**Pull request merged**
