### PR TITLE
Add 22.05 Quokka logo

### PR DESCRIPTION
**Pull request by dasJ**
Took me a couple of hours but this is what I came up with.
What do you think about it?
Source of the Quokka is https://www.flickr.com/photos/johnwturnbull/48096394967
quokka

### CODE REVIEW

**Comment by samueldr** [comment]
About licensing:

> Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0)

AFAIK @mogorman previously used CC0 content to make it easier to deal with.

I'm not really clear how we would need to handle the attribution bit correctly here for a release logo.

* * *

Some notes:

The quokka could be bigger, it seems small compared to previous animals.

I wonder, too, if leaving the quokka critter in the original orientation, rather than mirrored, would help or not with the problem that its face is surprisingly parallel with the lambdaflake. It looks off, almost as if it had been cut off for spacing, rather than being only parallel by chance.

In addition, more of a personal thing, but I'm not fond of the additional lambdaflake in the hands of the quokka critter friend.

**Comment by mogorman** [comment]
ya i think it is really bad idea for us to sell products / brand nix that don't have control the rights over.  I haven't started on logo for this release but I can this week.

**Comment by jonringer** [comment]
Aslo, I really like the animals "popping through" the nixos hole, makes them seem much more integrated and then they can usually be larger as well.

I do really like that it's holding a lambda :)

**Comment by dasJ** [comment]
Since the license is unclear I'm not going to continue working on this logo.
I thought about reaching out to the author, but I find it too unlikely that they are going to respond.

**Pull request closed without merging**
